# Generated by Django 5.2.8 on 2025-12-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_todo_duration_days_todo_end_time_alter_todo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='duration_days',
        ),
    ]
